---
- name: Interface Configuration
  cisco.ios.ios_l3_interfaces:
    config:
      - name: "{{ router_interfaces[inventory_hostname].interface }}"
        ipv4:
          - address: "{{ router_interfaces[inventory_hostname].ip_address }}"
    state: replaced
  register: int

- name: Show interface before configuration
  ansible.builtin.debug:
    msg: "{{ int.before | default('No before value returned') }}"

- name: Show generated commands
  ansible.builtin.debug:
    msg: "{{ int.commands | default('No commands returned') }}"

- name: Show interface after configuration
  ansible.builtin.debug:
    msg: "{{ int.after | default('No after value returned') }}"


